name: Update Wiki

on:
  push:
    branches:
      - master  # o la rama que desees

jobs:
  update_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Wiki
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          mkdir wiki
          echo "# Welcome to my Wiki" > wiki/Home.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update Wiki"
          git push
