name: Update Wiki

on:
  push:
    branches:
      - master  # o la rama que desees

jobs:
  update_wiki:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update Wiki
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          New-Item -ItemType Directory -Force -Path wiki
          Set-Content wiki/Home.md "# Welcome to my Wiki"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Update Wiki"
          git push